import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";

type Context = {
  params: {
    id: string;
  };
};

// üü° Prendre un rendez-vous
export async function PATCH(req: NextRequest, context: Context) {
  try {
    const appointmentId = context.params.id;
    const { patientId } = await req.json();

    const patient = await db.user.findUnique({
      where: { id: patientId },
    });

    if (!patient || patient.role !== "USER") {
      return NextResponse.json(
        { error: "Seuls les patients peuvent r√©server un rendez-vous" },
        { status: 403 }
      );
    }

    const appointment = await db.appointment.findUnique({
      where: { id: appointmentId },
    });

    if (!appointment) {
      return NextResponse.json(
        { error: "Rendez-vous introuvable" },
        { status: 404 }
      );
    }

    if (appointment.patientId) {
      return NextResponse.json(
        { error: "Ce rendez-vous est d√©j√† pris" },
        { status: 400 }
      );
    }

    const updatedAppointment = await db.appointment.update({
      where: { id: appointmentId },
      data: {
        patientId,
        status: "CONFIRMED",
      },
    });

    return NextResponse.json(updatedAppointment, { status: 200 });
  } catch (error) {
    console.error("Erreur lors du PATCH :", error);
    return NextResponse.json(
      { error: "Erreur lors de la r√©servation du rendez-vous" },
      { status: 500 }
    );
  }
}

export async function GET() {
  try {
    const pendingAppointments = await db.appointment.findMany({
      where: {
        status: "PENDING",
        patientId: null,
      },
    });
    return NextResponse.json(pendingAppointments, { status: 200 });
  } catch (error) {
    console.error("Erreur lors du GET :", error);
    return NextResponse.json(
      { error: "Erreur lors de la r√©cup√©ration des rendez-vous" },
      { status: 500 }
    );
  }
}
